name: Cypress Test

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn install
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn start
          browser: chrome

